# Generated by Django 3.0.6 on 2020-05-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools_list', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_registration_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=150)),
                ('student_class', models.IntegerField()),
                ('Student_roll_no', models.IntegerField()),
                ('student_subject', models.TextField()),
                ('student_school_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
        ),
    ]
