# Generated by Django 3.0.6 on 2020-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_class', models.CharField(max_length=20)),
                ('Student_roll_no', models.IntegerField()),
                ('student_subject', models.TextField()),
            ],
        ),
    ]
