# Generated by Django 3.0.6 on 2020-05-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200521_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='schools',
            new_name='schools_list',
        ),
    ]
