# Generated by Django 3.0.6 on 2020-05-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200521_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_name',
            new_name='student_school_name',
        ),
    ]
