# Generated by Django 3.0.6 on 2020-05-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200521_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_registration_no',
            field=models.IntegerField(default=0),
        ),
    ]
